version: '3'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_USER: ${PG_USER}
    ports:
      - ${PG_PORT}:${PG_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    links:
      - "db:${PG_HOST}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_CONNECTION_STRING: host=${PG_HOST} port=${PG_PORT} dbname=${PG_DB} user=${PG_USER} password=${PG_PASSWORD} sslmode=disable
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}

